### ISSUE TITLE
Customize builder UI

### ISSUE THREAD

**Issue by kasra-pak** [optimajet/formengine#5]
Hi, is there a way to hide or customize the toolbar components?
for example, hiding the preview button marked in the picture
![Capture](https://github.com/optimajet/formengine/assets/56297813/3b5ad33d-5a76-4b41-ab1e-1151e9420a45)

**Comment by sergeythrees** [comment]
Hi, @kasra-pak 
> Hi, is there a way to hide or customize the toolbar components?

We will add this feature in the next release. Thereafter уou can hide specific parts of the interface using CSS selectors. As example:
```css
.FormBuilder .Property > .CodeButton {
   display: none;
}
```
